spring:
  application:
    name: hmily-dubbo-provider-order
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
server:
  port: 6090

dubbo:
  scan:
    base-packages: cn.valjean.order
  protocol:
    name: dubbo
    port: 6091
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
  application:
    qosEnable: true
    qosPort: 6092
    qosAcceptForeignIp: true
    qos-enable-compatible: true
    qos-host-compatible: localhost
    qos-port-compatible: 6093
    qos-accept-foreign-ip-compatible: true
    qos-host: localhost
